In [99]:
import pandas as pd # data processing
import numpy as np # working with arrays
import matplotlib.pyplot as plt # visualization
import seaborn as sb # visualization
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

In [100]:
dataset = pd.read_csv("train.csv")

In [101]:
dataset

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [102]:
non_numeric_cols = dataset.select_dtypes(exclude=["int","float"]).columns

non_numeric_cols

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')

In [103]:
le = LabelEncoder()

for col in dataset.columns:
        if dataset[col].dtype == object:
            dataset[col] = le.fit_transform(dataset[col])

In [104]:
dataset

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3,65.0,8450,1,2,3,3,0,...,0,3,4,4,0,2,2008,8,4,208500
1,2,20,3,80.0,9600,1,2,3,3,0,...,0,3,4,4,0,5,2007,8,4,181500
2,3,60,3,68.0,11250,1,2,0,3,0,...,0,3,4,4,0,9,2008,8,4,223500
3,4,70,3,60.0,9550,1,2,0,3,0,...,0,3,4,4,0,2,2006,8,0,140000
4,5,60,3,84.0,14260,1,2,0,3,0,...,0,3,4,4,0,12,2008,8,4,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,3,62.0,7917,1,2,3,3,0,...,0,3,4,4,0,8,2007,8,4,175000
1456,1457,20,3,85.0,13175,1,2,3,3,0,...,0,3,2,4,0,2,2010,8,4,210000
1457,1458,70,3,66.0,9042,1,2,3,3,0,...,0,3,0,2,2500,5,2010,8,4,266500
1458,1459,20,3,68.0,9717,1,2,3,3,0,...,0,3,4,4,0,4,2010,8,4,142125
1459,1460,20,3,75.0,9937,1,2,3,3,0,...,0,3,4,4,0,6,2008,8,4,147500

In [105]:
dataset.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [110]:
nan_rows = dataset[dataset.isnull().any(axis=1)]
print(nan_rows)

        Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  \
7        8          60         3          NaN    10382       1      2
12      13          20         3          NaN    12968       1      2
14      15          20         3          NaN    10920       1      2
16      17          20         3          NaN    11241       1      2
24      25          20         3          NaN     8246       1      2
...    ...         ...       ...          ...      ...     ...    ...
1443  1444          30         3          NaN     8854       1      2
1446  1447          20         3          NaN    26142       1      2
1449  1450         180         4         21.0     1533       1      2
1450  1451          90         3         60.0     9000       1      2
1453  1454          20         3         90.0    17217       1      2

      LotShape  LandContour  Utilities  ...  PoolArea  PoolQC  Fence  \
7            0            3          0  ...         0       3      4
12           1            3          0  ...         0       3      4
14           0            3          0  ...         0       3      1
16           0            3          0  ...         0       3      4
24           0            3          0  ...         0       3      2
...        ...          ...        ...  ...       ...     ...    ...
1443         3            3          0  ...         0       3      4
1446         0            3          0  ...         0       3      4
1449         3            3          0  ...         0       3      4
1450         3            3          0  ...         0       3      4
1453         3            3          0  ...         0       3      4

      MiscFeature  MiscVal  MoSold  YrSold  SaleType  SaleCondition  SalePrice
7               2      350      11    2009         8              4     200000
12              4        0       9    2008         8              4     144000
14              4        0       5    2008         8              4     157000
16              2      700       3    2010         8              4     149000
24              4        0       5    2010         8              4     154000
...           ...      ...     ...     ...       ...            ...        ...
1443            4        0       5    2009         8              4     121000
1446            4        0       4    2010         8              4     157900
1449            4        0       8    2006         8              0      92000
1450            4        0       9    2009         8              4     136000
1453            4        0       7    2006         8              0      84500

[339 rows x 81 columns]

In [111]:
for col in dataset.columns:
        dataset[col] = dataset[col].fillna(0)

In [76]:
dataset.to_csv("new_train.csv", index=False)

In [ ]:
#Feature Engineering

In [112]:
x = dataset.drop(['SalePrice'],axis = 1)
y = dataset['SalePrice']

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=42)

In [113]:
x_train.isnull().sum().sum()

0

In [114]:
y_train.isnull().sum().sum()

0

In [116]:
from sklearn.ensemble import RandomForestRegressor

forest = RandomForestRegressor()

forest.fit(x_train,y_train)

RandomForestRegressor()

In [127]:
forest.score(x_test,y_test)

0.8978489183266359